runtime: nodejs14

#instance_class: F2

#handlers:
#  - url: /stylesheets
#    static_dir: stylesheets

#  - url: /.*
#    secure: always
#    redirect_http_response_code: 301
#    script: auto

env_variables:
  DB_ENV: "production"
  DB_SOCKET_PATH: "/cloudsql"
  DB_USER: "super-supper"
  DB_PASS: "rLjGc9LwFzOjMvsm"
  DB_NAME: "SS"
  CLOUD_SQL_CONNECTION_NAME: "super-supper:us-east1:super-supper"



#  rLjGc9LwFzOjMvsm

